table dim_wbs

	column wbs_id
		dataType: string
		sourceColumn: wbs_id

	column project_id
		dataType: string
		isHidden
		sourceColumn: project_id

	column wbs_name
		dataType: string
		sourceColumn: wbs_name

	column discipline
		dataType: string
		sourceColumn: discipline

	column origin_system
		dataType: string
		sourceColumn: origin_system

	partition dim_wbs = m
		mode: import
		source = ```
						let
							Source = Csv.Document(File.Contents(DataFolder & "dim_wbs.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
							Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
							Typed = Table.TransformColumnTypes(Promoted, {{"wbs_id", type text}, {"project_id", type text}, {"wbs_name", type text}, {"discipline", type text}, {"origin_system", type text}})
						in
							Typed
						```
