table dim_rfq

	/// Number of bid packages (RFQs) in context.
	measure 'RFQ Count' = DISTINCTCOUNT(dim_rfq[rfq_id])
		formatString: #,##0

	/// Sum of the engineer's cost estimate across RFQs in context.
	measure 'Engineers Estimate' = SUM(dim_rfq[engineers_estimate])
		formatString: $#,##0

	column rfq_id
		dataType: string
		sourceColumn: rfq_id

	column project_id
		dataType: string
		isHidden
		sourceColumn: project_id

	column wbs_id
		dataType: string
		isHidden
		sourceColumn: wbs_id

	column equipment_tag
		dataType: string
		sourceColumn: equipment_tag

	column material_category
		dataType: string
		sourceColumn: material_category

	column equipment_desc
		dataType: string
		sourceColumn: equipment_desc

	column engineers_estimate
		dataType: double
		summarizeBy: none
		sourceColumn: engineers_estimate

	column currency
		dataType: string
		sourceColumn: currency

	column issued_date
		dataType: dateTime
		sourceColumn: issued_date

	column bids_due_date
		dataType: dateTime
		sourceColumn: bids_due_date

	column required_on_site
		dataType: dateTime
		sourceColumn: required_on_site

	column status
		dataType: string
		sourceColumn: status

	column bidder_count
		dataType: int64
		summarizeBy: none
		sourceColumn: bidder_count

	column origin_system
		dataType: string
		sourceColumn: origin_system

	partition dim_rfq = m
		mode: import
		source = ```
						let
							Source = Csv.Document(File.Contents(DataFolder & "dim_rfq.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
							Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
							Typed = Table.TransformColumnTypes(Promoted, {{"rfq_id", type text}, {"project_id", type text}, {"wbs_id", type text}, {"equipment_tag", type text}, {"material_category", type text}, {"equipment_desc", type text}, {"engineers_estimate", type number}, {"currency", type text}, {"issued_date", type datetime}, {"bids_due_date", type datetime}, {"required_on_site", type datetime}, {"status", type text}, {"bidder_count", Int64.Type}, {"origin_system", type text}})
						in
							Typed
						```
